spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: jdbc:${DB_TYPE}://127.0.0.1:[forwardedPort]/${DB_SCHEMA}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIEND_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope: profile_nickname, profile_image
        provider:
          kakao: # registration 이름과 일치해야 함
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 사용자 정보에서 ID 추출 필드

ssh:
  remote_jump_host: ${REMOTE_JUMP_HOST} # ssh 연결할 중간 서버 주소, ec2 ip주소
  ssh_port: 22         # ssh 프로토콜 포트, 보통 22
  user: ${USER_NAME}  # ssh 연결할 사용자 계정
  private_key: ${PRIVATE_KEY_PATH}  # ssh 연결 시 사용할 개인키 파일 경로 => 접근하고자 하는 인스턴스의 주소
  database_url: ${DB_URL}   # rds url
  database_port: ${DB_PORT}  # rds 열려있는 포트번호

encrypt:
  secret-key: ${ENCRYPT_SECRET_KEY}

openvidu-url: ${OPEN_VIDU_URL}
openvidu-secret: ${OPEN_VIDU_SECRET}

jwt:
  secret: ${JWT_SECRET}

frontend-url: ${FRONTEND_URL}

special-gift:
  open-day: ${SPECIAL_GIFT_OPEN_DAY}

scheduler:
  event-day-transition-cron: "0 */10 * * * *"