package chocolate.chocoletter.common.exception;

import lombok.Getter;

@Getter
public enum ErrorMessage {

    /**
     * 400 Bad Request
     */
    ERR_MISSING_AUTHORIZATION_CODE,
    ERR_INVALID_REQUEST_FIELD,
    ERR_ALREADY_EXISTS_GIFT,
    ERR_ALREADY_ACCEPT_UNBOXING_INVITATION,
    ERR_INVALID_GIFT_TYPE,
    ERR_NOT_ENOUGH_PREVIEW_GIFT_COUNT,
    ERR_INVALID_QUERY_PARAMETER,
    ERR_NO_TOKEN,
    ERR_GIFT_ALREADY_OPENED,

    /**
     * 401 UNAUTHORIZED
     */
    ERR_UNAUTORIZED,
    ERR_REFRESH_TOKEN_EXPIRED,
    ERR_ACCESS_TOKEN_EXPIRED,
    ERR_INVALID_TOKEN,
    ERR_EMPTY_TOKEN,

    /**
     * 403 FORBIDDEN
     */
    ERR_FORBIDDEN,
    ERR_FORBIDDEN_UNBOXING_ROOM_ALREADY_END,
    ERR_FORBIDDEN_SPECIAL_BEFORE_DATE,
    ERR_FORBIDDEN_SPECIAL_AFTER_DATE,
    /**
     * /** 404 NOT_FOUND
     */
    ERR_NOT_FOUND,
    ERR_NOT_RESOURCE,
    ERR_NOT_FOUND_GIFT,
    ERR_NOT_FOUND_UNBOXING_ROOM,
    ERR_NOT_FOUND_GIFT_BOX,
    ERR_NOT_FOUND_USER,

    /**
     * 500 INTERNAL_SERVER_ERROR
     */
    ERR_INTERNAL_SERVER_ERROR,
    ERR_INTERNAL_SERVER_SQL_ERROR,
    ERR_INTERNAL_SERVER_ENCRYPTION_ERROR,
    ERR_INTERNAL_SERVER_DECRYPTION_ERROR

}
