name: Chat - Build & Push to Harbor and Update GitOps deploy tag

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "chocoletter-chat/**"

permissions:
  contents: write

jobs:
  build-push-update:
    # GitOps 리소스 푸시로 다시 재귀적으로 트리거되어 무한으로 호출되는 것을 막음
    if: github.actor != 'github-actions[bot]'
    runs-on: my-chocoletter-runner

    env:
      IMAGE_NAME: chocoletter-chat-image
      DEPLOY_FILE: chat/overlays/onprem/prod/kustomization.yaml
      HARBOR_REGISTRY: harbor.onprem.local
      HARBOR_PROJECT: son
      HARBOR_REPOSITORY: chocoletter-chat
      HARBOR_SCHEME: https

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image env
        run: |
          echo "IMAGE_REPOSITORY=${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${HARBOR_REPOSITORY}" >> $GITHUB_ENV

      - name: Login to Harbor
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          echo "${HARBOR_PASSWORD}" | docker login "${HARBOR_REGISTRY}" \
            --username "${HARBOR_USERNAME}" \
            --password-stdin

      - name: Calculate next image tag
        id: next_tag
        env:
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          JSON="$(curl -kfsSL \
            -u "${HARBOR_USERNAME}:${HARBOR_PASSWORD}" \
            "${HARBOR_SCHEME}://${HARBOR_REGISTRY}/api/v2.0/projects/${HARBOR_PROJECT}/repositories/${HARBOR_REPOSITORY}/artifacts?page_size=100")"
          
          NEXT_TAG="$(echo "$JSON" | python3 .github/scripts/calc_next_tag.py)"
          echo "NEXT_TAG=${NEXT_TAG}" >> $GITHUB_ENV

      - name: Build & Push Docker image
        run: |
          docker build --network host -t ${IMAGE_NAME}:${NEXT_TAG} ./chocoletter-chat
          docker tag ${IMAGE_NAME}:${NEXT_TAG} ${IMAGE_REPOSITORY}:${NEXT_TAG}
          docker push ${IMAGE_REPOSITORY}:${NEXT_TAG}

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: Son-Hunseo/chocoletter-gitops
          token: ${{ secrets.CHOCOLETTER_GITOPS_TOKEN }}
          path: chocoletter-gitops

      - name: Update kustomization.yaml image tag
        run: |
          sed -i -E \
            "s|(^[[:space:]]*newTag:[[:space:]]*).*$|\1\"${NEXT_TAG}\"|" \
            "chocoletter-gitops/${DEPLOY_FILE}"

      - name: Commit and push GitOps manifest
        run: |
          cd chocoletter-gitops
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add "${DEPLOY_FILE}"
          git commit -m "chore(gitops): bump chat image tag to ${NEXT_TAG}" || exit 0
          git push
